### ISSUE TITLE
hactoberfest-accepted

### ISSUE THREAD

**Issue by GeneralChauhan-1311** [GeneralChauhan-1311/Python-TicTacToe#2]
Modified Tic Tac Toe

**Comment by hackstar1** [comment]
I can help!

**Comment by krishnak3101** [comment]
Hi, I would like to contribute.

**Comment by GeneralChauhan** [comment]
ok you can do it if you want @krishnak3101 !

**Comment by jashanpahwa** [comment]
Hi, I want to contribute.

**Comment by hasan8130** [comment]
Hey, @GeneralChauhan-1311  please assign me this issue under hactoberfest'21.
